spring.application.name=Postfolio

# DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Pi@31416

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port (optional)
server.port=8080

# Netty-socketio configuration
socket.host=localhost
socket.port=9092


gemini.api.key=AIzaSyDyu3V1zVQxZYZb-MMnP0UJMIT2WXRI-KY

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent

stripe.secretKey=sk_test_51S1igdHPpcxZT7HbbWluSpkKo729cKqyvK9g5N3oMDV6FWsbVF2MuSvx8zAFp1mDrmioaHN9TdoL6HvecTX5VZZS00aTkUBx1S
