spring.application.name=stripe
server.port=9991
debug=true
stripe.return.url=http://localhost:3000
stripe.key.public=pk_test_51S1igdHPpcxZT7Hb3oX2pD081tkKg3Ewt7k1QFNdYu5tY1azAq08jQcH5cVb1I5NL6aP6RV74nj3iTgVPiZuuyUy00byrxWFTc
stripe.secret.key=sk_test_51S1igdHPpcxZT7HbbWluSpkKo729cKqyvK9g5N3oMDV6FWsbVF2MuSvx8zAFp1mDrmioaHN9TdoL6HvecTX5VZZS00aTkUBx1S
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
